### ISSUE TITLE
As the DAO, I want to show the number of vaults, so that investors can deposit into vaults

### ISSUE THREAD

**Issue by bitcoinbrisbane** [horse-link/horse.link#1]
Ill create a vault registry contract

**Comment by Manik-Aggarwal** [comment]
I want to work on this issue. Could you assign it to me.?

**Comment by bitcoinbrisbane** [comment]
Sounds great! I’ll post the graph api

**Comment by bitcoinbrisbane** [comment]
@Manik-Aggarwal are you still keen to work on this?  I have a local API now too.
