### ISSUE TITLE
Roll back to upper case

### ISSUE THREAD

**Issue by bitcoinbrisbane** [horse-link/horse.link#21]
Check for nulls, make api meta data upper case.

**Comment by ArshErgon** [comment]
Hey @bitcoinbrisbane what does` check for nulls` mean?

**Comment by bitcoinbrisbane** [comment]
> Hey @bitcoinbrisbane what does` check for nulls` mean? and there's no api_meta_data anywhere.

The code is actually in the API repo. https://github.com/horse-link/api.horse.link/blob/main/src/index.js#L35-L43

Will need to check that venueMnemonic has a value.

```javascript
  const meetings = response.data.meetings.map(item => {
    const meeting = {};
    meeting.id = item.venueMnemonic; //;
    meeting.name = item.meetingName; //.toUpperCase();
    meeting.location = item.location; //.toUpperCase();
    meeting.date = item.meetingDate;

    return meeting;
  });
```

**Comment by HritikR** [comment]
Hi @bitcoinbrisbane, like this?
```
const meetings = response.data.meetings.map(item => {
    const meeting = {};
    meeting.id = item.venueMnemonic ? item.venueMnemonic : "";
    meeting.name = item.meetingName.toUpperCase();
    meeting.location = item.location.toUpperCase();
    meeting.date = item.meetingDate;

    return meeting;
  });
```

**Comment by bitcoinbrisbane** [comment]
Looks good!

**Comment by HritikR** [comment]
@bitcoinbrisbane should add an issue on the API repository.  i would like to send a PR

**Comment by bitcoinbrisbane** [comment]
> @bitcoinbrisbane should add an issue on the API repository. i would like to send a PR

Thanks @HritikR see https://github.com/horse-link/api.horse.link/issues/2
