### ISSUE TITLE
As a test user, I want to receive mock USDT, so that I can wager or deposit to vaults

### ISSUE THREAD

**Issue by bitcoinbrisbane** [horse-link/horse.link#27]
* Simple form to issue mock usdt so punters can wager or deposit
* Make a menu Faucet linking to /faucet
* Post to the api and then display the tx id https://api.horselink.com/faucet

![image](https://user-images.githubusercontent.com/8411406/187052830-0be5f48e-e6ee-447e-82e5-1307bbf534d7.png)

**Comment by 0xPranjl** [comment]
can you assign it to me??

**Comment by bitcoinbrisbane** [comment]
sure!

________________________________

**Comment by 0xPranjl** [comment]
ok 
But I have a question where is the mock usdt send api?

**Comment by bitcoinbrisbane** [comment]
> ok But I have a question where is the mock usdt send api?

I was just about to add to the ticket.  You can post to https://api.horselink.com/faucet

Code is here if you need the response object https://github.com/horse-link/api.horse.link/blob/main/src/index.js#L227-L247

**Comment by 0xPranjl** [comment]
ok thanks

**Comment by 0xPranjl** [comment]
how much mock usdt should be send by the faucet to a user??

**Comment by bitcoinbrisbane** [comment]
> how much mock usdt should be send by the faucet to a user??

Can be any amount.  $100 or $1,000 sounds about right.

**Comment by 0xPranjl** [comment]
get request for other endpoints works well but Post request on https://api.horse.link/faucet throws cors error

**Comment by bitcoinbrisbane** [comment]
> get request for other endpoints works well but Post request on https://api.horse.link/faucet throws cors error

Thanks, i fixed a json issue, ill republish tonight.

**Comment by bitcoinbrisbane** [comment]
@0xPranjl  Faucet api fixed, will deploy tonight

![image](https://user-images.githubusercontent.com/8411406/188551399-e40275b8-0909-467b-abb2-055d3671d8b2.png)
