### ISSUE TITLE
As a liquidity provider, I want to see the Vaults history, so that I know tokens are coming in and out.

### ISSUE THREAD

**Issue by MikeyRobertson** [horse-link/horse.link#83]
Show all deposit/withdraw and which vault it was to/from in a list of transactions down the page.  Table should be the follwing and be fetched from api.horse.link/vault/history

- Amount
- Type (deposit or withdraw)
- Time
- User

**Comment by pondpiu** [comment]
- put deposit/withdraw modal under button
- clicking anywhere else expand the row showing another inner table
