### ISSUE TITLE
Faucet Added to site

### ISSUE THREAD

**Issue by MikeyRobertson** [horse-link/horse.link#87]
Faucet Added to site > We need to be able to claim ETH / DAI / USDT
Screenshot added where Faucet link should go
![Untitled](https://user-images.githubusercontent.com/95732950/196564511-0a3a91ab-4104-4645-8863-7658d9ab7020.png)

Faucet screen should look something like this;
![Untitled2](https://user-images.githubusercontent.com/95732950/196565121-913ae21e-8f9e-4402-a5fc-502520687fe9.png)

**Comment by pondpiu** [comment]
DIA and USDT claims is live. 
ETH hasn't been implemented

**Comment by bitcoinbrisbane** [comment]
@pondpiu can we close this guy?
