### ISSUE TITLE
As a punter, I want to see the previous form of the horse, so that I can make a good bet.

### ISSUE THREAD

**Issue by MikeyRobertson** [horse-link/horse.link#89]
On the Runners page (when you select a race) we want to add FORM column, we also want to shift WEIGHT to the left and have FORM next to the WIN price.  picture attached.
![Untitled](https://user-images.githubusercontent.com/95732950/196827943-f7b27692-d998-4267-aa2c-176da7e5f31d.png)

**Comment by bitcoinbrisbane** [comment]
Ill need to update the API
